# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20170204_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='user_here',
            new_name='user',
        ),
    ]
